# Site settings
title: Ben Scott
email: ben@benscott.co.uk
description: > # this means to ignore newlines until "baseurl:"
  <p>Some thoughts and ramblings on data, science, music and digital openness.</p>
  <p>Currently lead architect of the Natural History Museum's Data Portal.</p>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.benscott.co.uk" # the base hostname & protocol for your site
twitter_username: benjaminscott
github_username:  benscott
drupal_id: 149339
linkedin_id: 9085417
stackoverflow_username: bens

exclude:
  - "bower.json"

# Build settings
markdown: kramdown
