# Site settings
title: Ben Scott
email: ben@benscott.co.uk
description: > # ignore newlines until "baseurl:"
  <p>Lead architect of the Natural History Museum's Data Portal.</p>
  <p>Thoughts on open data, science, music and politics.</p>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.benscott.co.uk" # the base hostname & protocol for your site

exclude:
  - "bower.json"

# Build settings
markdown: kramdown
